### PR TITLE
ISSUE 29 Add type script support

### LINKED ISSUE #29: ✨ [Feature request]: Add TypeScript Support
Currently the `yarn create-play` command creates the play in JavaScript(JSX). Please add the support to create play scaffolding based on TypeScript.

### PR DESCRIPTION
**Pull request by koustov**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)
Closes #29 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by koustov** [comment]
@atapas  the PR looks good now.

**Review by atapas — COMMENTED** [review]
Only comment I have about this change

image

Why is it needed?

**Comment by koustov** [comment]
> Only comment I have about this change
> 
> image
> 
> Why is it needed?



> Only comment I have about this change
> 
> image
> 
> Why is it needed?

Unwanted check-in. Removed now

**Comment by atapas** [comment]
@koustov Should we add some text in the create play md that you can now create a play using both typescript and javascript.. kind of highlighting it?

**Comment by koustov** [comment]
> @koustov Should we add some text in the create play md that you can now create a play using both typescript and javascript.. kind of highlighting it?

That would be nice I will get it added

**Review by atapas — APPROVED** [review]
Looks good.

**Comment by atapas** [comment]
@all-contributors please add @koustov  for Code

**Pull request merged**
