### PR TITLE
Install puppeteer@latest as a dev dependency

### LINKED ISSUE #141: [Bug]: The puppeteer error while building
### Discussed in https://github.com/atapas/react-play/discussions/112

<div type='discussions-op-text'>

<sup>Originally posted by **atapas** April 28, 2022</sup>
@erayalkis 

I am seeing this intermittent error in the log and it fails the build. Do you think, we have a fix for it? Starting this discussion, if you want to get to a root-cause, welcome. When you have a fix, let's convert this one to an issue.

image
</div>

### PR DESCRIPTION
**Pull request by erayalkis**
# Description

This PR installs puppeteer's latest version as a dev dependency, and aims to fix #141. 

Fixes #141 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Ran build tests multiple times as the bug happens at random, got no errors so far and upgrading puppeteer seems to have fixed the issue.

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by atapas** [comment]
@erayalkis Please resolve the conflicts to make ready for merge.

**Comment by erayalkis** [comment]
> @erayalkis Please resolve the conflicts to make ready for merge.

Apologies, I forgot to resolve the conflicts after the TS update 😄 Everything seems okay now, thank you for reminding me!

**Review by atapas — CHANGES_REQUESTED** [review]
@erayalkis, isn't that missing a comma?

**Comment by erayalkis** [comment]
> @erayalkis, isn't that missing a comma?

Oops, it is! I'll fix it ASAP!

**Review by atapas — APPROVED** [review]

**Pull request merged**
