### PR TITLE
A Registration form with validation

### PR DESCRIPTION
**Pull request by Deepak8717**
# Description

A new registration form with validation without any library 

Fixes # (issue)
New project
## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by atapas** [comment]
@Deepak8717 Kindly resolve conflicts

**Comment by Deepak8717** [comment]
@atapas resolved the conflict.

**Comment by atapas** [comment]
> @atapas resolved the conflict.

@Deepak8717 Resolve.

**Comment by atapas** [comment]
@Deepak8717  Could you please create an issue for the play and associate with the PR to start the review?

**Comment by atapas** [comment]
> @atapas resolved the conflict.

It still shows the conflict

image

**Comment by Deepak8717** [comment]
raised a new one with updated branch. this branch needs to updated with recent merge.

**Pull request closed without merging**
