### PR TITLE
Fix plays route failture

### LINKED ISSUE #66: 🐛 [Bug report]: Deep Linking for the Plays fails. It shows a blank page.
**Describe the bug**
If you hit any play URL directly, it gives a blank page. It should show the play details page.

**To Reproduce**
1. Open your browser
2. Paste this URL: https://www.reactplay.io/plays/social-card and hit enter
3. You will see a blank screen
4. Error in the browser console

image

**Expected behavior**
The Play should be accessible with deep linking

**Screenshots**

**Desktop (please complete the following information):**
All

**Smartphone (please complete the following information):**
 All

**Additional context**
Moving to play detail from the play list works well.

### PR DESCRIPTION
**Pull request by 6km**
# Description

I've fixed the error that shows when you open a 'play' link by passing the state to the component itself

Fixes #66 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

1. Open your browser
2. Paste this URL: https://react-play-git-fork-6km-main-atapas.vercel.app/plays/social-card and hit enter

# Checklist:

- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by atapas — CHANGES_REQUESTED** [review]
@6km Great, thanks for adding the fix for 8 existing plays. There is one more place the fix is required.

We generate the play files using the PlopJS template for any new play. So you need to update the template according to this fix. The template file is: https://github.com/atapas/react-play/blob/main/plop-templates/component.hbs

Once updated, please try the `yarn create-play` command to create a sample play and test that locally for routing and basic sanity. Please do not commit the files generated out of the sample play test. Thanks a ton.

**Comment by 6km** [comment]
@atapas can you review the PR again?

**Comment by atapas** [comment]
> @atapas can you review the PR again?

Can you please confirm that you have created the new play creation  workflow in the UI and tested the routing fix with a new play?

I can test it as well if you haven't done already.

**Comment by 6km** [comment]
@atapas I've tested the new play creation workflow and everything is okay.
image

**Review by atapas — COMMENTED** [review]
@6km looks good.

**Review by atapas — APPROVED** [review]

**Comment by 6km** [comment]
@atapas Thanks for approving my changes

**Comment by atapas** [comment]
@all-contributors please add @6km for Code

**Comment by atapas** [comment]
> @atapas Thanks for approving my changes

Thanks for fixing it and the Twitter link too. In case you share your experience on Twitter, don't forget tag ReactPlayIO 💚.

Keep contributing. @6km

**Comment by 6km** [comment]
@atapas You're welcome. all of your projects are awesome 😉.

**Pull request merged**
