### PR TITLE
Fix embeds not working as intended

### LINKED ISSUE #90: 🐛 [Bug report]: Meta tags not being properly detected in some sites
**Describe the bug**

The new way of handling meta tags doesn't work in some sites/apps.

**To Reproduce**
1. Go to any site that supports embeds
2. Paste any link from the site
3. See that no embed data shows up

**Expected behavior**

The embed data is supposed to show up without any issues.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome (irrelevant to problem)
 -
**Additional context**

I'm assuming this is caused by the meta tags initially not being available inside the index.html file.

**I will start working on fixing this issue ASAP**

### PR DESCRIPTION
**Pull request by erayalkis**
# Description

This PR adds the meta tags back into the index.html file, and adds the react-snap package. I noticed that the new way of handling meta tags doesn't work for some sites, as they do *not* run JavaScript to fetch the metadata, meaning that react-helmet doesn't get a chance to update the meta tags. 

This PR adds react-snap to fix this issue. Now, every time we run npm build, react-snap will go through all of the available routes and generate a static HTML page for them. Meaning that any site and app will have a **static** HTML file available for them, accessible even without JavaScript.

Fixes #90

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

I disabled JavaScript on various browsers and visited all available pages on the site. I can confirm that the meta tags show up without any issues. This should now hopefully fix the embeds on social media sites.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

# Notes:

This new fix *should* add the embed functionality, but if anything doesn't work as intended, I'll push a bugfix ASAP! These meta tags turned out to be a much more complex issue than I initally thought ! 😄 😄

### CODE REVIEW

**Comment by erayalkis** [comment]
Thats odd, the build ran perfectly on localhost and it gives me a 404 when I try to view the details :(

**Comment by erayalkis** [comment]
Seems like an issue with puppeteer, this should hopefully fix it!

**Comment by erayalkis** [comment]
That's really odd, the new config should allow puppeteer to run without any issues

**Comment by atapas** [comment]
> > That's really odd, the new config should allow puppeteer to run without any issues
> 
> # Log
> [21:23:47] Cloning github.com/atapas/react-play (Branch: main, Commit: [332fa55](https://github.com/atapas/react-play/commit/332fa550ee4c3e497913b8147a638739734d04eb)) [21:23:49] Cloning completed: 1.714s [21:23:49] Installing build runtime... [21:23:53] Build runtime installed: 3.860s [21:23:54] Looking up build cache... [21:23:57] Build cache downloaded [41.26 MB]: 3144.446ms [21:23:57] Detected package.json [21:23:57] Installing dependencies... [21:23:58] yarn install v1.22.17 [21:23:58] [1/4] Resolving packages... [21:23:59] [2/4] Fetching packages... [21:24:24] [3/4] Linking dependencies... [21:24:24] warning " > @testing-library/user-event@13.5.0" has unmet peer dependency "@testing-library/dom@>=7.21.4". [21:24:24] warning "react-helmet > react-side-effect@2.1.1" has incorrect peer dependency "react@^16.3.0 || ^17.0.0". [21:24:24] warning "react-organizational-chart > @emotion/css > @emotion/babel-plugin@11.7.2" has unmet peer dependency "@babel/core@^7.0.0". [21:24:24] warning "react-organizational-chart > @emotion/css > @emotion/babel-plugin > @babel/plugin-syntax-jsx@7.16.7" has unmet peer dependency "@babel/core@^7.0.0-0". [21:24:24] warning "react-scripts > tailwindcss@3.0.12" has unmet peer dependency "autoprefixer@^10.0.2". [21:24:24] warning "react-scripts > eslint-config-react-app > eslint-plugin-flowtype@8.0.3" has unmet peer dependency "@babel/plugin-syntax-flow@^7.14.5". [21:24:24] warning "react-scripts > eslint-config-react-app > eslint-plugin-flowtype@8.0.3" has unmet peer dependency "@babel/plugin-transform-react-jsx@^7.14.9". [21:24:24] warning "react-scripts > react-dev-utils > fork-ts-checker-webpack-plugin@6.5.0" has unmet peer dependency "typescript@>= 2.7". [21:24:24] warning "react-scripts > eslint-config-react-app > @typescript-eslint/eslint-plugin > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta". [21:24:24] warning " > react-shimmer-effect@1.0.9" has incorrect peer dependency "react@^16.8.1". [21:24:24] warning " > react-shimmer-effect@1.0.9" has incorrect peer dependency "react-dom@^16.8.1". [21:24:36] [4/4] Building fresh packages... [21:24:43] success Saved lockfile. [21:24:43] Done in 45.67s. [21:24:44] Running "yarn run build" [21:24:44] yarn run v1.22.17 [21:24:44] $ react-scripts build [21:24:46] Creating an optimized production build... [21:25:11] Compiled with warnings. [21:25:11] [21:25:11] src/common/home/Home.jsx [21:25:11] Line 29:6: React Hook useEffect has a missing dependency: 'setFilterQuery'. Either include it or remove the dependency array react-hooks/exhaustive-deps [21:25:11] [21:25:11] Search for the keywords to learn more about each warning. [21:25:11] To ignore, add // eslint-disable-next-line to the line before. [21:25:11] [21:25:11] File sizes after gzip: [21:25:11] [21:25:11] 101.58 kB build/static/js/main.79ae8b27.js [21:25:11] 8.1 kB build/static/css/main.011a351c.css [21:25:11] 1.78 kB build/static/js/787.7c42db31.chunk.js [21:25:11] [21:25:11] The project was built assuming it is hosted at /. [21:25:11] You can control this with the homepage field in your package.json. [21:25:11] [21:25:11] The build folder is ready to be deployed. [21:25:11] You may serve it with a static server: [21:25:11] [21:25:11] yarn global add serve [21:25:11] serve -s build [21:25:11] [21:25:11] Find out more about deployment here: [21:25:11] [21:25:11] https://cra.link/deployment [21:25:11] [21:25:11] $ react-snap [21:25:13] ️️️💬 console.log at /: Unrecognized feature: 'clipboard-write'. [21:25:13] ️️️💬 console.log at /: JSHandle@array [21:25:13] ️️️💬 console.log at /: JSHandle@array [21:25:13] ️️️💬 console.log at /: JSHandle@array [21:25:13] ️️️💬 console.log at /: JSHandle@array [21:25:15] ✅ crawled 1 out of 6 (/) [21:25:15] ️️️💬 console.log at /plays: searchTerm [21:25:15] ️️️💬 console.log at /plays: filterQuery JSHandle@object [21:25:15] ️️️💬 console.log at /plays/movies: data JSHandle@array [21:25:15] ️️️💬 console.log at /plays: searchTerm [21:25:15] ️️️💬 console.log at /plays: filterQuery JSHandle@object [21:25:15] 💬 console.log at /plays/movies: { [21:25:15] id: 'pl-0004', [21:25:15] name: 'Movies', [21:25:15] description: 'A list of movies from API call.', [21:25:15] component: {}, [21:25:15] path: '/plays/movies', [21:25:15] level: 'Intermediate', [21:25:15] tags: 'Fetch Data, Hooks', [21:25:15] github: 'atapas', [21:25:15] featured: true, [21:25:15] blog: 'https://blog.openreplay.com/understanding-the-container-component-pattern-with-react-hooks' [21:25:15] } [21:25:15] ️️️💬 console.log at /plays/movies: data JSHandle@array [21:25:15] ️️️💬 console.log at /plays: Cover image not found for the play States [21:25:15] ️️️💬 console.log at /plays: Setting the default cover image... [21:25:15] 💬 console.log at /plays/org-tree: { [21:25:15] id: 'pl-0005', [21:25:15] name: 'Organization Tree', [21:25:15] description: 'A simple org tree', [21:25:15] component: {}, [21:25:15] path: '/plays/org-tree', [21:25:15] level: 'Intermediate', [21:25:15] tags: 'Recursion, Tree', [21:25:15] github: 'green-roots', [21:25:15] featured: true [21:25:15] } [21:25:15] ️️️💬 console.log at /plays/movies: data JSHandle@object [21:25:15] ️️️💬 console.log at /plays/movies: data JSHandle@object [21:25:16] ⚠️ warning: 404 page title does not contain "404" string [21:25:16] ✅ crawled 2 out of 6 (/404.html) [21:25:16] ✅ crawled 3 out of 12 (/plays) [21:25:16] ✅ crawled 4 out of 12 (/plays/org-tree) [21:25:16] 💬 console.log at /plays/counter: { [21:25:16] id: 'pl-counter', [21:25:16] name: 'Counter', [21:25:16] description: 'A simple counter which increments the value upto a certain limit!', [21:25:16] component: {}, [21:25:16] path: '/plays/counter', [21:25:16] level: 'Beginner', [21:25:16] tags: 'JSX, State, Props', [21:25:16] github: 'murtuzaalisurti', [21:25:16] featured: true [21:25:16] } [21:25:16] 💬 console.log at /plays/why-react: TypeError: Cannot read property 'id' of null [21:25:18] 🔥 pageerror at /plays/why-react: TypeError: Cannot read property 'id' of null [21:25:18] at id (plays/why-react/WhyReact.jsx:10:10) [21:25:18] at c (../node_modules/react-dom/cjs/react-dom.production.min.js:166:136) [21:25:18] at Nh (../node_modules/react-dom/cjs/react-dom.production.min.js:289:385) [21:25:18] at Lk (../node_modules/react-dom/cjs/react-dom.production.min.js:279:378) [21:25:18] at Kk (../node_modules/react-dom/cjs/react-dom.production.min.js:279:309) [21:25:18] at Jk (../node_modules/react-dom/cjs/react-dom.production.min.js:279:169) [21:25:18] at yk (../node_modules/react-dom/cjs/react-dom.production.min.js:270:442) [21:25:18] at Dk (../node_modules/react-dom/cjs/react-dom.production.min.js:268:420) [21:25:18] at d (../node_modules/scheduler/cjs/scheduler.production.min.js:13:202) [21:25:18] 💬 console.log at /plays/clock: { [21:25:18] id: 'pl-0002', [21:25:18] name: 'Clock', [21:25:18] description: 'This application shows the current time and it increases every second', [21:25:18] component: {}, [21:25:18] path: '/plays/clock', [21:25:18] level: 'Beginner', [21:25:18] tags: 'JSX, Schedule', [21:25:18] github: 'atapas', [21:25:18] blog: 'https://blog.greenroots.info', [21:25:18] video: 'https://youtube.com/tapasadhikary' [21:25:18] } [21:25:18] ✅ crawled 5 out of 12 (/plays/clock) [21:25:18] ✅ crawled 10 out of 12 (/plays/counter) [21:25:18] ✅ crawled 11 out of 12 (/plays/movies) [21:25:18] ✅ crawled 12 out of 12 (/plays/why-react) [21:25:18] [21:25:18] error Command failed with exit code 1. [21:25:18] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command. [21:25:18] Error: Command "yarn run build" exited with 1

The why-react play seems throwing error. Just fyi

**Comment by atapas** [comment]
> So, everything runs normally and react-snap crawls each page without any issues, but for some reason it crashes at the last second? This is really weird, I'll try to fix it ASAP, sorry this took so long !

No worries, I see it gives id thanks for one if the play. I see it in the log. That may give some lead.

Btw, take it easy. No hurry 😀

**Comment by erayalkis** [comment]
Seems like it was caused by WhyReact using react-dom functions for it's id. This should now hopefully fix it!

**Comment by erayalkis** [comment]
LET'S GOOOOO finally got it !!!!!😄😄

**Comment by atapas** [comment]
> LET'S GOOOOO finally got it !!!!!😄😄

First thing I will review it tomorrow morning and merge. Good work.

**Comment by erayalkis** [comment]
> > LET'S GOOOOO finally got it !!!!!😄😄
> 
> First thing I will review it tomorrow morning and merge. Good work.

Alrighty! Thank you so much, I'm glad I can be a part of this amazing project !!!

**Review by atapas — APPROVED** [review]

**Pull request merged**
