### PR TITLE
[Feature] Auto update user readme

### LINKED ISSUE #207: ✨ [Feature request]: Automatically updating play readme based on user input
**Is your feature request related to a problem? Please describe.**
Not a problem

**Describe the solution you'd like**
The idea of this issue is to create a boilerplate readme for every play automatically.

A possible readme template (Unrelated section should be removed)

---

## play-name
detailed play description

## Play Demographic
Language: <language used>
Level : <level>

## Creator Information
User: <username>
Gihub Link: <user github link>
Blog: <blog link>
Video: <video link>

## Implementation Details
Update your implementation idea and details here

## Consideration
Update all considerations(if any)

## Resources
Update external resources(if any)

---
For further suggestion/details, initiate a thread under [discussion](https://github.com/atapas/react-play/discussions)

**Describe alternatives you've considered**
NA

**Additional context**
#200

### PR DESCRIPTION
**Pull request by naiknareshh**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/atapas/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Added feature request to automatically update user readme based on user inputs. no dependencies were added for this change.

Fixes #207 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

# Checklist:

- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by naiknareshh** [comment]
This is Ready for Review

**Comment by koustov** [comment]
@naiknareshh can you share a screenshot of readme from newly created play?

**Comment by naiknareshh** [comment]
Generated Readme File -

image

Preview - 

image

**Comment by atapas** [comment]
> Generated Readme File -
> 
> image
> 
> Preview -
> 
> image

@koustov let me know if any changes are required. Otherwise, it is LGTM

**Review by koustov — APPROVED** [review]
LGTM

**Comment by naiknareshh** [comment]
Not sure why Merging is still blocked for this. let me know if I am missing something.

**Review by atapas — APPROVED** [review]
LGTM

**Comment by atapas** [comment]
> Not sure why Merging is still blocked for this. let me know if I am missing something.

Nope, nothing from your side. It is just the sequence we can get to PR to approve and merge. Good Work @naiknareshh

**Pull request merged**
